import type { AdminMemberDetailDraft, AdminMemberListRow } from './adminMemberTypes'

export const adminMemberListStats = {
  totalValue: '14.850',
  totalTrend: '+340 bu hafta',
  syncLabel: 'Veritabanı senkronizasyonu',
  syncStatus: 'Tamamlandı',
  activeValue: '13.920',
  activeRate: '%93.7 Aktiflik',
  activeNote: 'Son 30 gün içi oturum',
  activeBadge: 'Yüksek Etkileşim',
  newValue: '860',
  newTrend: '+18.4%',
  newNote: 'Maç haftası akını',
  newBadge: 'Pik Noktası',
  staffValue: '18',
  staffNote: 'Yetkili',
  staffDetail: 'Hiyerarşik roller',
  staffBadge: '2 Rol Tanımlı',
}

export const adminMemberListRows: AdminMemberListRow[] = [
  {
    id: '1092',
    username: 'BordoFırtına61',
    email: 'bordo.firtina61@trabzonly.net',
    memberCode: '#MBR-1092',
    role: 'admin',
    roleLabel: 'Yönetici',
    status: 'active',
    statusLabel: 'Aktif',
    postsLabel: '42 Gönderi',
    squadsLabel: '18 Kadro Analizi',
    registeredAt: '12.08.2021',
    isVerified: true,
    initials: 'BF',
    avatarTone: 'from-primary to-primary-container',
    actionLabel: 'Askıya Al',
    actionTone: 'danger',
  },
  {
    id: '2415',
    username: 'KuzeyKale61',
    email: 'kemal.ozkan@gmail.com',
    memberCode: '#MBR-2415',
    role: 'moderator',
    roleLabel: 'Moderatör',
    status: 'active',
    statusLabel: 'Aktif',
    postsLabel: '19 Gönderi',
    squadsLabel: '9 Kadro Analizi',
    registeredAt: '04.03.2022',
    initials: 'KK',
    avatarTone: 'from-secondary to-primary-container',
    actionLabel: 'Askıya Al',
    actionTone: 'danger',
  },
  {
    id: '3301',
    username: 'DozerEfsane',
    email: 'hasan.ts@outlook.com',
    memberCode: '#MBR-3301',
    role: 'member',
    roleLabel: 'Üye',
    status: 'active',
    statusLabel: 'Aktif',
    postsLabel: '8 Gönderi',
    squadsLabel: '5 Kadro Analizi',
    registeredAt: '19.09.2023',
    initials: 'DE',
    avatarTone: 'from-primary-container to-secondary',
    actionLabel: 'Askıya Al',
    actionTone: 'danger',
  },
  {
    id: '4890',
    username: 'FırtınaAvniAker',
    email: 'mert61@yandex.com',
    memberCode: '#MBR-4890',
    role: 'member',
    roleLabel: 'Üye',
    status: 'passive',
    statusLabel: 'Pasif (Hareketsiz)',
    postsLabel: '1 Gönderi',
    squadsLabel: '0 Kadro Analizi',
    registeredAt: '15.01.2024',
    initials: 'FA',
    avatarTone: 'from-tertiary-container to-primary',
    actionLabel: 'Aktifleştir',
    actionTone: 'success',
  },
  {
    id: '5120',
    username: 'TrabzonluMimar',
    email: 'serkan.aydin@arch.com',
    memberCode: '#MBR-5120',
    role: 'editor',
    roleLabel: 'Editör',
    status: 'active',
    statusLabel: 'Aktif',
    postsLabel: '34 Gönderi',
    squadsLabel: '12 Kadro Analizi',
    registeredAt: '28.02.2024',
    badgeLabel: 'Köşe Yazarı',
    initials: 'TM',
    avatarTone: 'from-secondary to-primary',
    actionLabel: 'Askıya Al',
    actionTone: 'danger',
  },
  {
    id: '6240',
    username: 'KaradenizDalgasi',
    email: 'murat.xz.dnz@gmail.com',
    memberCode: '#MBR-6240',
    role: 'member',
    roleLabel: 'Üye',
    status: 'suspended',
    statusLabel: 'Askıda (Kural İhlali)',
    postsLabel: '5 Gönderi',
    squadsLabel: '1 Kadro Analizi',
    registeredAt: '10.06.2024',
    initials: 'KD',
    avatarTone: 'from-primary to-tertiary-container',
    actionLabel: 'Engeli Kaldır',
    actionTone: 'restore',
  },
]

const roleSummaries: Record<string, string> = {
  admin:
    'Yönetici rolü içerik onaylama, kadro ve quiz moderasyonu ile kullanıcı ve sistem denetimi yetkilerine tam kapsamlı olarak sahiptir.',
  moderator:
    'Moderatör rolü içerik inceleme, kadro raporları ve topluluk yorum moderasyonu yetkilerine sahiptir.',
  editor:
    'Editör rolü makale, maç raporları ve quiz hazırlama yetkilerine sahiptir.',
  member: 'Standart portal katılımcısı gönderi, kadro ve quiz etkileşimine açıktır.',
}

export const defaultAdminMemberDetailDraft: AdminMemberDetailDraft = {
  id: '1092',
  memberCode: '#MBR-1092',
  registryNo: '1092',
  username: 'BordoFırtına61',
  email: 'bordo.firtina61@trabzonly.net',
  bio: "1967'den beri bordomavi sevda. Akyazı Doğu Tribünü kombine sahibi. Taktik analizler ve altyapı oyuncu takibi meraklısı. 'Bize Her Yer Trabzon!'",
  role: 'admin',
  roleSummary: roleSummaries.admin,
  isActive: true,
  isVerified: true,
  emailVerified: true,
  verifiedLabel: 'Onaylı Taraftar',
  registeredAt: '12 Ağustos 2021, 19:67',
  registerChannel: 'Kayıt Kanalı: Web Portal (Desktop)',
  lastLogin: 'Bugün, 15:42',
  lastLoginMeta: 'Web Masaüstü • Aktif Oturum #8812',
  location: 'Trabzon, Türkiye (Doğrulandı)',
  ipMask: 'IP Mask: 176.240.***.*** (Statik)',
  twoFactorActive: true,
  passwordHashLabel: 'Şifre Kriptolu Argon2id Hash',
  postsCount: '42',
  postsNote: 'Analiz, Makale & Köşe Yazısı',
  squadsCount: '18',
  squadsNote: 'Haftalık Taktik Tahtası',
  quizzesCount: '15',
  quizzesNote: 'Ortalama Başarı: %88.5',
  likesCount: '1.420',
  likesNote: 'Topluluk Teşekkürü',
  reputationScore: 98,
  reputationLabel: '98 / 100 • Güvenilir Üye',
  reputationNote:
    'Spam, toksik yorum ve kural ihlali filtresinden sıfır ceza puanı ile geçmiştir.',
  engagementMonths: [
    { label: 'Ekim', height: 'h-8' },
    { label: 'Kasım', height: 'h-12' },
    { label: 'Aralık', height: 'h-10' },
    { label: 'Ocak', height: 'h-16' },
    { label: 'Şubat', height: 'h-14' },
    { label: 'Mart', height: 'h-20' },
  ],
  auditItems: [
    {
      id: 'a1',
      icon: 'verified_user',
      title: 'Son Güvenlik Doğrulaması',
      detail: 'E-posta & 2FA anahtarı onaylandı',
      date: '14.02.2025',
    },
    {
      id: 'a2',
      icon: 'task_alt',
      title: 'Şikayet / Rapor Sayısı',
      detail: '0 Rapor (Kusursuz Sicil)',
      badge: 'Temiz',
      badgeTone: 'bg-secondary-container text-on-secondary-container',
    },
    {
      id: 'a3',
      icon: 'policy',
      title: 'Hesap Kısıtlaması & Ceza',
      detail: 'Hiçbir kısıtlama uygulanmadı',
      badge: 'Yok',
      badgeTone: 'bg-surface-container-high text-on-surface-variant',
    },
  ],
  previewBadge: 'Kombinelı Taraftar',
  previewRole: 'Yönetici',
  membershipYear: '2021',
  initials: 'BF',
  avatarTone: 'from-primary to-primary-container',
}

export function getAdminMemberDetailDraft(
  memberId: string | undefined,
): AdminMemberDetailDraft {
  if (!memberId || memberId === '1092' || memberId === '1') {
    return defaultAdminMemberDetailDraft
  }

  const row = adminMemberListRows.find((item) => item.id === memberId)

  if (!row) {
    return {
      ...defaultAdminMemberDetailDraft,
      id: memberId,
      memberCode: `#MBR-${memberId}`,
      registryNo: memberId,
    }
  }

  return {
    ...defaultAdminMemberDetailDraft,
    id: row.id,
    memberCode: row.memberCode,
    registryNo: row.id,
    username: row.username,
    email: row.email,
    role: row.role,
    roleSummary: roleSummaries[row.role] ?? roleSummaries.member,
    isActive: row.status === 'active',
    isVerified: Boolean(row.isVerified),
    postsCount: row.postsLabel.split(' ')[0] ?? '0',
    squadsCount: row.squadsLabel.split(' ')[0] ?? '0',
    previewRole: row.roleLabel,
    membershipYear: row.registeredAt.slice(-4),
    initials: row.initials,
    avatarTone: row.avatarTone,
  }
}

export const adminMemberRoleOptions = [
  { value: 'admin', label: 'Yönetici (Sistem Konsolu Tam Erişim)' },
  { value: 'moderator', label: 'Moderatör (İçerik & Kadro İnceleme)' },
  { value: 'editor', label: 'Editör (Makale, Maç Raporları & Quiz Hazırlama)' },
  { value: 'member', label: 'Onaylı Taraftar (Rozetli Topluluk Üyesi)' },
  { value: 'community', label: 'Topluluk Üyesi (Standart Portal Katılımcısı)' },
] as const
