import type { AdminHubProfile, AdminShellProfile } from './adminHubTypes'

export const adminShellProfile: AdminShellProfile = {
  brandTitle: 'TRABZONLY',
  brandSubtitle: 'Yönetim Masası',
  navHeading: 'Operasyonel Menü',
  adminName: 'Dozer Cemil',
  adminRole: 'Sistem Yöneticisi',
  adminInitials: 'DC',
  footerLeft: '© 2024 Trabzonly Yönetim Merkezi • Bordo-Mavi Dijital Arşiv Sistemi',
  footerRight: 'Bize Her Yer Trabzon',
  navItems: [
    { id: 'overview', label: 'Genel bakış', to: '/yonetim', icon: 'dashboard' },
    {
      id: 'players',
      label: 'Oyuncular',
      to: '/yonetim/oyuncular',
      icon: 'groups',
      badge: '28',
      badgeTone: 'count',
    },
    { id: 'stats', label: 'İstatistikler', to: '/yonetim/istatistikler', icon: 'bar_chart' },
    {
      id: 'injuries',
      label: 'Sakatlıklar',
      to: '/yonetim/sakatliklar',
      icon: 'healing',
      badgeTone: 'alert',
    },
    { id: 'seasons', label: 'Sezonlar', to: '/yonetim/sezonlar', icon: 'calendar_month' },
    { id: 'positions', label: 'Pozisyonlar', to: '/yonetim/pozisyonlar', icon: 'grid_view' },
    { id: 'categories', label: 'Kategoriler', to: '/yonetim/kategoriler', icon: 'category' },
    { id: 'quizzes', label: 'Quizler', to: '/yonetim/quizler', icon: 'quiz' },
    { id: 'members', label: 'Üyeler', to: '/yonetim/uyeler', icon: 'people' },
    {
      id: 'roles',
      label: 'Roller',
      to: '/yonetim/roller',
      icon: 'admin_panel_settings',
    },
  ],
}

export const adminHubProfile: AdminHubProfile = {
  title: 'Yönetim Paneli',
  description:
    'Trabzonly içerik ve kadro verilerini yönet. Karadeniz Fırtınası dijital arşiv, taraftar katılım ve resmi kadro yönetim konsolu.',
  permissionLabel: 'Yetki Düzeyi',
  permissionValue: 'Tam Yetkili Editör',
  systemStatusLabel: 'Sistem',
  systemStatusValue: 'Çevrimiçi',
  versionLabel: 'v2.4',
  breadcrumbRoot: 'Yönetim Paneli',
  breadcrumbCurrent: 'Genel Bakış & Hızlı Modüller',
  modules: [
    {
      id: 'players',
      title: 'Oyuncular',
      description: 'Oyuncu kayıtlarını ekle, profil kartlarını ve transfer durumlarını düzenle.',
      categoryLabel: 'Kadro & Lisans',
      badgeLabel: '28 Oyuncu',
      badgeTone: 'neutral',
      icon: 'groups',
      to: '/yonetim/oyuncular',
    },
    {
      id: 'stats',
      title: 'İstatistikler',
      description:
        'Sezon bazlı oyuncu ve maç performans metriklerini, gol/asist verilerini yönet.',
      categoryLabel: 'Performans Havuzu',
      badgeLabel: '2024-25',
      badgeTone: 'info',
      icon: 'bar_chart',
      to: '/yonetim/istatistikler',
    },
    {
      id: 'injuries',
      title: 'Sakatlıklar',
      description:
        'Sakatlık kayıtlarını, sağlık raporlarını ve sahalara tahmini dönüş sürelerini yönet.',
      categoryLabel: 'Sağlık & Tedavi',
      badgeLabel: '1 Aktif Tedavi',
      badgeTone: 'warning',
      icon: 'healing',
      to: '/yonetim/sakatliklar',
    },
    {
      id: 'seasons',
      title: 'Sezonlar',
      description: 'Süper Lig ve Avrupa sezonlarını tanımla, arşiv periyotlarını yapılandır.',
      categoryLabel: 'Lig & Arşiv',
      badgeLabel: 'Aktif Sezon',
      badgeTone: 'success',
      icon: 'calendar_month',
      to: '/yonetim/sezonlar',
    },
    {
      id: 'positions',
      title: 'Pozisyonlar',
      description:
        'Pozisyon sözlüğünü ve taktik tahtası saha rollerini (ST, OOS, DOS, STP) yönet.',
      categoryLabel: 'Taktik Tanımlar',
      badgeLabel: '14 Mevki',
      badgeTone: 'neutral',
      icon: 'grid_view',
      to: '/yonetim/pozisyonlar',
    },
    {
      id: 'categories',
      title: 'Kategoriler',
      description: 'Gönderi ve taktik analiz kategorilerini, etiket filtrelerini yönet.',
      categoryLabel: 'İçerik Taksonomisi',
      badgeLabel: '8 Kategori',
      badgeTone: 'neutral',
      icon: 'category',
      to: '/yonetim/kategoriler',
    },
    {
      id: 'quizzes',
      title: 'Quizler',
      description: 'Trabzonspor tarih ve hafıza testleri oluştur, soruları düzenle ve yayınla.',
      categoryLabel: 'Taraftar Etkileşimi',
      badgeLabel: '18 Yayında',
      badgeTone: 'info',
      icon: 'quiz',
      to: '/yonetim/quizler',
    },
    {
      id: 'members',
      title: 'Üyeler',
      description:
        'Kayıtlı taraftar listesini görüntüle, üye profillerini ve tribün puanlarını incele.',
      categoryLabel: 'Topluluk Divanı',
      badgeLabel: '4.280 Kayıt',
      badgeTone: 'neutral',
      icon: 'people',
      to: '/yonetim/uyeler',
    },
    {
      id: 'roles',
      title: 'Roller',
      description: 'Yetki şablonlarını, moderatör ve yazar erişim matrislerini yönet.',
      categoryLabel: 'Erişim & Güvenlik',
      badgeLabel: 'Admin & Yazar',
      badgeTone: 'neutral',
      icon: 'admin_panel_settings',
      to: '/yonetim/roller',
    },
  ],
}
