import type { AdminStatisticFormDraft, AdminStatisticListRow } from './adminStatisticTypes'

export const adminStatisticListStats = {
  archiveValue: '142',
  archiveNote: '12 Sezonluk resmi müsabaka kaydı',
  topScorerGoals: '14',
  topScorerMeta: 'GOL / 19 MAÇ',
  topScorerName: 'Simon Banza',
  topScorerDetail: '#17 • ST',
  assistLeaderValue: '9',
  assistLeaderMeta: 'ASİST / 20 MAÇ',
  assistLeaderName: 'Edin Višća',
  assistLeaderDetail: '#7 • RW',
  cleanSheetValue: '8',
  cleanSheetMeta: 'GOLLÜ MAÇSIZ / 21 HAFTA',
  cleanSheetName: 'Uğurcan Çakır',
  cleanSheetDetail: '#1 • KAPTAN',
}

export const adminStatisticListRows: AdminStatisticListRow[] = [
  {
    id: '1',
    playerName: 'Simon Banza',
    number: 17,
    positionCode: 'ST',
    positionGroup: 'att',
    nationality: 'Kongo DC',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 19,
    minutesLabel: "1.620′",
    minutes: 1620,
    goals: 14,
    assists: 3,
    yellowCards: 2,
    redCards: 0,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'SB',
    avatarTone: 'from-primary to-secondary',
  },
  {
    id: '2',
    playerName: 'Edin Višća',
    number: 7,
    positionCode: 'RW',
    positionGroup: 'att',
    nationality: 'Bosna Hersek',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 20,
    minutesLabel: "1.540′",
    minutes: 1540,
    goals: 5,
    assists: 9,
    yellowCards: 1,
    redCards: 0,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'EV',
    avatarTone: 'from-secondary to-primary-container',
  },
  {
    id: '3',
    playerName: 'Uğurcan Çakır',
    number: 1,
    positionCode: 'GK',
    positionGroup: 'gk',
    nationality: 'Türkiye',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 21,
    minutesLabel: "1.890′",
    minutes: 1890,
    goals: 0,
    assists: 0,
    yellowCards: 3,
    redCards: 0,
    cleanSheets: 8,
    saves: 64,
    goalsConceded: 19,
    isVerified: true,
    initials: 'UÇ',
    avatarTone: 'from-tertiary-container to-primary',
  },
  {
    id: '4',
    playerName: 'Batista Mendy',
    number: 6,
    positionCode: 'DM',
    positionGroup: 'mid',
    nationality: 'Fransa',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 18,
    minutesLabel: "1.510′",
    minutes: 1510,
    goals: 2,
    assists: 1,
    yellowCards: 6,
    redCards: 1,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'BM',
    avatarTone: 'from-primary-container to-secondary',
  },
  {
    id: '5',
    playerName: 'Stefan Savić',
    number: 15,
    positionCode: 'CB',
    positionGroup: 'def',
    nationality: 'Karadağ',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 14,
    minutesLabel: "1.220′",
    minutes: 1220,
    goals: 1,
    assists: 0,
    yellowCards: 4,
    redCards: 0,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'SS',
    avatarTone: 'from-[#0b3a55] to-primary',
  },
  {
    id: '6',
    playerName: 'Denis Drăguș',
    number: 70,
    positionCode: 'LW/ST',
    positionGroup: 'att',
    nationality: 'Romanya',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 16,
    minutesLabel: "980′",
    minutes: 980,
    goals: 4,
    assists: 2,
    yellowCards: 2,
    redCards: 0,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'DD',
    avatarTone: 'from-secondary to-[#1a040b]',
  },
  {
    id: '7',
    playerName: 'Pedro Malheiro',
    number: 2,
    positionCode: 'RB',
    positionGroup: 'def',
    nationality: 'Portekiz',
    season: '2024/25',
    team: 'Trabzonspor',
    matches: 19,
    minutesLabel: "1.680′",
    minutes: 1680,
    goals: 1,
    assists: 4,
    yellowCards: 3,
    redCards: 0,
    cleanSheets: null,
    saves: null,
    goalsConceded: null,
    initials: 'PM',
    avatarTone: 'from-primary to-tertiary-container',
  },
]

export const adminStatisticPlayerOptions = [
  { id: '1', label: 'Simon Banza (#17)', name: 'Simon Banza', number: '17', position: 'Santrafor (ST)' },
  { id: '2', label: 'Edin Višća (#7)', name: 'Edin Višća', number: '7', position: 'Sağ Kanat (RW)' },
  { id: '3', label: 'Uğurcan Çakır (#1)', name: 'Uğurcan Çakır', number: '1', position: 'Kaleci (GK)' },
  { id: '4', label: 'Batista Mendy (#6)', name: 'Batista Mendy', number: '6', position: 'Ön Libero (DM)' },
  { id: '5', label: 'Stefan Savić (#15)', name: 'Stefan Savić', number: '15', position: 'Stoper (CB)' },
  { id: '6', label: 'Denis Drăguș (#70)', name: 'Denis Drăguș', number: '70', position: 'Sol Kanat (LW)' },
  { id: '7', label: 'Pedro Malheiro (#2)', name: 'Pedro Malheiro', number: '2', position: 'Sağ Bek (RB)' },
]

export const adminStatisticSeasonOptions = ['2024/25 Sezonu', '2023/24 Sezonu', '2022/23 Sezonu']

export const adminStatisticTeamOptions = [
  'Trabzonspor A-Takım',
  'Trabzonspor U19',
  'Rezerv Takım',
]

export const defaultAdminStatisticFormDraft: AdminStatisticFormDraft = {
  id: '1',
  recordCode: '#STAT-2024-BANZA17 • AKTİF SEZON',
  playerId: '1',
  playerName: 'Simon Banza',
  playerNumber: '17',
  playerPosition: 'Santrafor (ST)',
  season: '2024/25 Sezonu',
  team: 'Trabzonspor A-Takım',
  matches: '19',
  minutes: '1620',
  goals: '14',
  goalsBreakdown: 'LİG: 12 • KUPA: 2',
  assists: '3',
  yellowCards: '2',
  redCards: '0',
  cleanSheets: '0',
  saves: '0',
  goalsConceded: '0',
  minutesPerGoalLabel: '115.7',
  minutesPerGoalNote: 'Süper Lig ortalamasının üzerinde',
  previewPositionBadge: 'FORVET',
  lastUpdated: 'Bugün, 16:45 (Dozer Cemil)',
  seasonStatus: '2024/25 Süper Lig (Canlı Sezon)',
  apiSyncLabel: 'Opta / TFF Canlı',
  initials: 'SB',
  avatarTone: 'from-primary to-secondary',
}

export const emptyAdminStatisticFormDraft: AdminStatisticFormDraft = {
  id: '',
  recordCode: '#STAT-YENİ',
  playerId: '1',
  playerName: 'Simon Banza',
  playerNumber: '17',
  playerPosition: 'Santrafor (ST)',
  season: '2024/25 Sezonu',
  team: 'Trabzonspor A-Takım',
  matches: '0',
  minutes: '0',
  goals: '0',
  goalsBreakdown: 'LİG: 0 • KUPA: 0',
  assists: '0',
  yellowCards: '0',
  redCards: '0',
  cleanSheets: '0',
  saves: '0',
  goalsConceded: '0',
  minutesPerGoalLabel: '—',
  minutesPerGoalNote: 'Veri girildikçe hesaplanır',
  previewPositionBadge: 'FORVET',
  lastUpdated: '—',
  seasonStatus: '2024/25 Süper Lig (Canlı Sezon)',
  apiSyncLabel: 'Opta / TFF Canlı',
  initials: 'SB',
  avatarTone: 'from-primary to-secondary',
}

export function getAdminStatisticFormDraft(
  statisticId: string | undefined,
): AdminStatisticFormDraft {
  if (!statisticId) {
    return emptyAdminStatisticFormDraft
  }

  if (statisticId === defaultAdminStatisticFormDraft.id || statisticId === '1') {
    return defaultAdminStatisticFormDraft
  }

  const row = adminStatisticListRows.find((item) => item.id === statisticId)

  if (!row) {
    return {
      ...emptyAdminStatisticFormDraft,
      id: statisticId,
      recordCode: `#STAT-${statisticId}`,
    }
  }

  const minutesPerGoal =
    row.goals > 0 ? (row.minutes / row.goals).toFixed(1) : '—'

  return {
    ...emptyAdminStatisticFormDraft,
    id: row.id,
    recordCode: `#STAT-2024-${row.playerName.split(' ').pop()?.toUpperCase()}${row.number}`,
    playerId: row.id,
    playerName: row.playerName,
    playerNumber: String(row.number),
    playerPosition: row.positionCode,
    season: `${row.season} Sezonu`,
    team: row.team === 'Trabzonspor' ? 'Trabzonspor A-Takım' : row.team,
    matches: String(row.matches),
    minutes: String(row.minutes),
    goals: String(row.goals),
    assists: String(row.assists),
    yellowCards: String(row.yellowCards),
    redCards: String(row.redCards),
    cleanSheets: String(row.cleanSheets ?? 0),
    saves: String(row.saves ?? 0),
    goalsConceded: String(row.goalsConceded ?? 0),
    minutesPerGoalLabel: minutesPerGoal,
    previewPositionBadge:
      row.positionGroup === 'gk'
        ? 'KALECİ'
        : row.positionGroup === 'def'
          ? 'SAVUNMA'
          : row.positionGroup === 'mid'
            ? 'ORTA SAHA'
            : 'FORVET',
    initials: row.initials,
    avatarTone: row.avatarTone,
  }
}
