import type {
  AdminPlayerFormDraft,
  AdminPlayerListRow,
  AdminPlayerListStats,
  AdminPlayerReportStrip,
} from './adminPlayerTypes'

export const adminPlayerReportStrip: AdminPlayerReportStrip = {
  kicker: 'A TAKIM RAPORU',
  message: '2024/25 Süper Lig Lisans Listesi Güncellendi (TFF Tescilli 28 Oyuncu)',
  marketValueTotal: '€94.30M',
  foreignQuota: '12 / 14',
}

export const adminPlayerListStats: AdminPlayerListStats = {
  totalLabel: 'TOPLAM KADRO',
  totalValue: '28 Oyuncu',
  activeLabel: 'MÜSABIK / AKTİF',
  activeValue: '25 Oyuncu',
  inactiveLabel: 'REVİR / PASİF',
  inactiveValue: '3 Oyuncu',
  positionDistribution: '4 KL • 9 DEF • 8 OS • 7 FOR',
  positionNote: 'Dengeli rotasyon yapısı',
  averageAge: '26.4 Yıl',
  averageAgeNote: 'Lig standardında ideal',
  nationalCount: '11 A Milli',
  nationalNote: '8 Farklı Milli Takım',
  reportTitle: 'KADRO RAPORU (PDF)',
  reportSubtitle: 'Müsabaka Listesi',
  reportNote: 'Haftalık maç kadrosu dökümü',
}

export const adminPlayerListRows: AdminPlayerListRow[] = [
  {
    id: '17',
    number: 17,
    fullName: 'Simon Banza',
    secondaryName: 'Simon Luc Banza',
    positionLabel: 'Santrafor (ST)',
    positionGroup: 'att',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Kongo DC',
    nationalityFlag: '🇨🇩',
    age: 28,
    marketValueLabel: '€16.00M',
    marketValueMillions: 16,
    status: 'active',
    statusLabel: 'Aktif',
    initials: 'SB',
    avatarTone: 'from-primary to-secondary',
  },
  {
    id: '7',
    number: 7,
    fullName: 'Edin Višća',
    secondaryName: 'Sağ Kanat',
    positionLabel: 'Sağ Kanat (RW)',
    positionGroup: 'att',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Bosna-Hersek',
    nationalityFlag: '🇧🇦',
    age: 34,
    marketValueLabel: '€2.20M',
    marketValueMillions: 2.2,
    status: 'active',
    statusLabel: 'Aktif',
    isViceCaptain: true,
    initials: 'EV',
    avatarTone: 'from-secondary to-primary-container',
  },
  {
    id: '6',
    number: 6,
    fullName: 'Batista Mendy',
    secondaryName: 'Defansif Orta Saha',
    positionLabel: 'Ön Libero (DOS)',
    positionGroup: 'mid',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Fransa',
    nationalityFlag: '🇫🇷',
    age: 24,
    marketValueLabel: '€10.00M',
    marketValueMillions: 10,
    status: 'active',
    statusLabel: 'Aktif',
    initials: 'BM',
    avatarTone: 'from-primary-container to-secondary',
  },
  {
    id: '1',
    number: 1,
    fullName: 'Uğurcan Çakır',
    secondaryName: 'A Milli Takım Kalecisi',
    positionLabel: 'Kaleci (KL)',
    positionGroup: 'gk',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Türkiye',
    nationalityFlag: '🇹🇷',
    age: 28,
    marketValueLabel: '€8.50M',
    marketValueMillions: 8.5,
    status: 'active',
    statusLabel: 'Aktif',
    isCaptain: true,
    initials: 'UÇ',
    avatarTone: 'from-tertiary-container to-primary',
  },
  {
    id: '24',
    number: 24,
    fullName: 'Stefano Denswil',
    secondaryName: 'Sol Stoper',
    positionLabel: 'Stoper (STP)',
    positionGroup: 'def',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Surinam',
    nationalityFlag: '🇸🇷',
    age: 31,
    marketValueLabel: '€1.80M',
    marketValueMillions: 1.8,
    status: 'injured',
    statusLabel: 'Sakat',
    initials: 'SD',
    avatarTone: 'from-[#0b3a55] to-primary',
  },
  {
    id: '99',
    number: 99,
    fullName: 'Enis Destan',
    secondaryName: 'Genç Santrafor',
    positionLabel: 'Santrafor (ST)',
    positionGroup: 'att',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Türkiye',
    nationalityFlag: '🇹🇷',
    age: 22,
    marketValueLabel: '€4.50M',
    marketValueMillions: 4.5,
    status: 'active',
    statusLabel: 'Aktif',
    initials: 'ED',
    avatarTone: 'from-primary to-tertiary-container',
  },
  {
    id: '70',
    number: 70,
    fullName: 'Denis Drăguș',
    secondaryName: 'Sol Kanat / Forvet',
    positionLabel: 'Sol Kanat (LW)',
    positionGroup: 'att',
    squadLabel: 'Trabzonspor A Takım',
    squadFilter: 'first-team',
    nationality: 'Romanya',
    nationalityFlag: '🇷🇴',
    age: 25,
    marketValueLabel: '€4.00M',
    marketValueMillions: 4,
    status: 'active',
    statusLabel: 'Aktif',
    initials: 'DD',
    avatarTone: 'from-secondary to-[#1a040b]',
  },
]

export const adminPlayerNationalityOptions = [
  'Kongo DC (Demokratik Kongo Cumhuriyeti)',
  'Türkiye',
  'Fransa',
  'Nijerya',
  'Brezilya',
  'Hırvatistan',
  'Bosna-Hersek',
  'Romanya',
  'Surinam',
]

export const adminPlayerPrimaryPositions = [
  'Kaleci (GK)',
  'Stoper (CB)',
  'Sol Bek (LB)',
  'Sağ Bek (RB)',
  'Ön Libero (CDM)',
  'Merkez Orta Saha (CM)',
  'On Numara (CAM)',
  'Sol Kanat (LW)',
  'Sağ Kanat (RW)',
  'Santrafor (ST)',
]

export const adminPlayerSecondaryPositions = [
  '— Yok —',
  'İkinci Forvet / Kanat Forvet',
  'Sağ Kanat',
  'Sol Kanat',
  'On Numara',
]

export const adminPlayerSquadOptions = [
  'Trabzonspor A Takım',
  'Trabzonspor U19 Gelişim',
  'Kiralık Gönderilenler',
]

export const defaultAdminPlayerFormDraft: AdminPlayerFormDraft = {
  id: '17',
  recordCode: '#TS-17',
  fullName: 'Simon Bokote Banza',
  jerseyNumber: '17',
  birthDate: '1996-08-13',
  nationality: 'Kongo DC (Demokratik Kongo Cumhuriyeti)',
  preferredFoot: 'right',
  isActiveInSquad: true,
  heightCm: '189',
  weightKg: '83',
  primaryPosition: 'Santrafor (ST)',
  secondaryPosition: 'İkinci Forvet / Kanat Forvet',
  currentSquad: 'Trabzonspor A Takım',
  contractEnd: '2025-06-30',
  marketValue: '16000000',
  annualSalary: '2100000',
  tacticalProfile:
    "2024-2025 sezonunda Braga'dan kiralık olarak kadroya katılan dinamik santrafor. Ceza sahası içi bitiriciliği ve sırtı dönük oyun kurma yeteneğiyle öne çıkıyor. Hava toplarındaki hakimiyeti hücum organizasyonlarında kilit rol oynuyor.",
  createdBy: 'Dozer Cemil (Yönetici)',
  lastUpdated: 'Dün, 18:42',
  tffLicenseCode: '1967-TZ-8842',
  contractTypeLabel: 'KİRALIK',
  initials: 'SB',
  avatarTone: 'from-primary to-secondary',
}

export const emptyAdminPlayerFormDraft: AdminPlayerFormDraft = {
  id: '',
  recordCode: '#TS-YENİ',
  fullName: '',
  jerseyNumber: '',
  birthDate: '',
  nationality: 'Türkiye',
  preferredFoot: 'right',
  isActiveInSquad: true,
  heightCm: '',
  weightKg: '',
  primaryPosition: 'Santrafor (ST)',
  secondaryPosition: '— Yok —',
  currentSquad: 'Trabzonspor A Takım',
  contractEnd: '',
  marketValue: '',
  annualSalary: '',
  tacticalProfile: '',
  createdBy: 'Dozer Cemil (Yönetici)',
  lastUpdated: '—',
  tffLicenseCode: '—',
  contractTypeLabel: 'KALICI',
  initials: '?',
  avatarTone: 'from-surface-container-high to-primary-container',
}

export function getAdminPlayerFormDraft(playerId: string | undefined): AdminPlayerFormDraft {
  if (!playerId) {
    return emptyAdminPlayerFormDraft
  }

  if (playerId === defaultAdminPlayerFormDraft.id || playerId === '17') {
    return defaultAdminPlayerFormDraft
  }

  const row = adminPlayerListRows.find((player) => player.id === playerId)

  if (!row) {
    return {
      ...emptyAdminPlayerFormDraft,
      id: playerId,
      recordCode: `#TS-${playerId}`,
      fullName: `Oyuncu ${playerId}`,
    }
  }

  return {
    ...emptyAdminPlayerFormDraft,
    id: row.id,
    recordCode: `#TS-${row.number}`,
    fullName: row.fullName,
    jerseyNumber: String(row.number),
    nationality: row.nationality,
    primaryPosition: row.positionLabel,
    currentSquad: row.squadLabel,
    marketValue: String(Math.round(row.marketValueMillions * 1_000_000)),
    isActiveInSquad: row.status === 'active',
    initials: row.initials,
    avatarTone: row.avatarTone,
    tacticalProfile: `${row.fullName} için taktiksel profil notu henüz tamamlanmadı.`,
  }
}
