import { type PlayerCardData } from './playerDirectoryTypes'

export const PAGE_SIZE = 12

export const placeholderPlayers: PlayerCardData[] = [
  {
    id: '1',
    number: 1,
    name: 'Uğurcan Çakır',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'gk',
    positionCode: 'KL',
    positionLabel: 'KALECİ',
    rating: 9.4,
    age: 28,
    height: '1.91 m',
    note: 'Trabzonspor Altyapısı',
    marketValue: 8_500_000,
    badge: { label: 'KAPTAN', tone: 'bordo' },
    stats: [
      { label: 'Maç', value: '28' },
      { label: 'Golsüz Maç', value: '11' },
      { label: 'Kurtarış %', value: '%79.4' },
    ],
    tone: 'from-[#5A0E27] to-[#1A040B]',
  },
  {
    id: '2',
    number: 99,
    name: 'Simon Banza',
    nationality: 'D.R. KONGO',
    isDomestic: false,
    positionGroup: 'fwd',
    positionCode: 'FOR',
    positionLabel: 'SANTRFOR',
    rating: 9.1,
    age: 28,
    height: '1.89 m',
    note: 'Kiralık (Braga)',
    marketValue: 16_000_000,
    badge: { label: 'GOL KRALI ADAYI', tone: 'mavi' },
    stats: [
      { label: 'Maç', value: '24' },
      { label: 'Gol', value: '12' },
      { label: 'Asist', value: '3' },
    ],
    tone: 'from-[#3f2900] to-[#1A040B]',
  },
  {
    id: '3',
    number: 7,
    name: 'Edin Višća',
    nationality: 'BOSNA HERSEK',
    isDomestic: false,
    positionGroup: 'fwd',
    positionCode: 'SK',
    positionLabel: 'SAĞ KANAT',
    rating: 8.8,
    age: 34,
    height: '1.72 m',
    note: 'Şampiyon Kadro',
    marketValue: 2_200_000,
    badge: { label: 'ASİST LİDERİ', tone: 'bordo' },
    stats: [
      { label: 'Maç', value: '26' },
      { label: 'Gol', value: '5' },
      { label: 'Asist', value: '9' },
    ],
    tone: 'from-[#12648e] to-[#1A040B]',
  },
  {
    id: '4',
    number: 6,
    name: 'Batista Mendy',
    nationality: 'FRANSA',
    isDomestic: false,
    positionGroup: 'mid',
    positionCode: 'DOS',
    positionLabel: 'ÖN LİBERO',
    rating: 8.9,
    age: 24,
    height: '1.91 m',
    note: 'Angers SCO Transferi',
    marketValue: 9_500_000,
    badge: { label: 'TOP ÇALMA LİDERİ', tone: 'neutral' },
    stats: [
      { label: 'Maç', value: '27' },
      { label: 'Pas %', value: '%88.2' },
      { label: 'Top Çalma', value: '64' },
    ],
    tone: 'from-[#544245] to-[#1A040B]',
  },
  {
    id: '5',
    number: 8,
    name: 'Okay Yokuşlu',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'mid',
    positionCode: 'MC',
    positionLabel: 'ORTA SAHA',
    rating: 8.6,
    age: 30,
    height: '1.91 m',
    note: "West Bromwich'ten Dönüş",
    marketValue: 5_500_000,
    stats: [
      { label: 'Maç', value: '22' },
      { label: 'Gol', value: '2' },
      { label: 'Asist', value: '1' },
    ],
    tone: 'from-[#5A0E27] to-[#34302b]',
  },
  {
    id: '6',
    number: 44,
    name: 'Arseniy Batagov',
    nationality: 'UKRAYNA',
    isDomestic: false,
    positionGroup: 'def',
    positionCode: 'STP',
    positionLabel: 'STOPER',
    rating: 8.6,
    age: 22,
    height: '1.91 m',
    note: 'Dnipro-1 Transferi',
    marketValue: 7_000_000,
    stats: [
      { label: 'Maç', value: '25' },
      { label: 'Top Çalma', value: '41' },
      { label: 'Hava %', value: '%72' },
    ],
    tone: 'from-[#12648e] to-[#1A040B]',
  },
  {
    id: '7',
    number: 18,
    name: 'Muhammed Cham',
    nationality: 'AVUSTURYA',
    isDomestic: false,
    positionGroup: 'mid',
    positionCode: 'MO',
    positionLabel: 'OFANSİF OS',
    rating: 8.3,
    age: 24,
    height: '1.80 m',
    note: 'Clermont Foot Transferi',
    marketValue: 6_000_000,
    stats: [
      { label: 'Maç', value: '20' },
      { label: 'Gol', value: '4' },
      { label: 'Asist', value: '6' },
    ],
    tone: 'from-[#3f2900] to-[#5A0E27]',
  },
  {
    id: '8',
    number: 3,
    name: 'Eren Elmalı',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'def',
    positionCode: 'SB',
    positionLabel: 'SOL BEK',
    rating: 8.1,
    age: 24,
    height: '1.80 m',
    note: 'Kasımpaşa Transferi',
    marketValue: 4_500_000,
    stats: [
      { label: 'Maç', value: '23' },
      { label: 'Asist', value: '3' },
      { label: 'Orta %', value: '%31' },
    ],
    tone: 'from-[#5A0E27] to-[#12648e]',
  },
  {
    id: '9',
    number: 54,
    name: 'Onuralp Çevikkan',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'gk',
    positionCode: 'KL',
    positionLabel: 'KALECİ',
    rating: 7.4,
    age: 19,
    height: '1.93 m',
    note: 'Altyapı Yükselişi',
    marketValue: 1_200_000,
    stats: [
      { label: 'Maç', value: '3' },
      { label: 'Golsüz Maç', value: '1' },
      { label: 'Kurtarış %', value: '%71' },
    ],
    tone: 'from-[#34302b] to-[#1A040B]',
  },
  {
    id: '10',
    number: 11,
    name: 'Ozan Tufan',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'mid',
    positionCode: 'MC',
    positionLabel: 'ORTA SAHA',
    rating: 8.0,
    age: 29,
    height: '1.82 m',
    note: 'Hull City Dönüşü',
    marketValue: 3_800_000,
    stats: [
      { label: 'Maç', value: '18' },
      { label: 'Gol', value: '3' },
      { label: 'Asist', value: '2' },
    ],
    tone: 'from-[#5A0E27] to-[#544245]',
  },
  {
    id: '11',
    number: 19,
    name: 'Umut Bozok',
    nationality: 'TÜRKİYE',
    isDomestic: true,
    positionGroup: 'fwd',
    positionCode: 'FOR',
    positionLabel: 'FORVET',
    rating: 7.9,
    age: 28,
    height: '1.78 m',
    note: 'Lorient Transferi',
    marketValue: 3_500_000,
    stats: [
      { label: 'Maç', value: '17' },
      { label: 'Gol', value: '6' },
      { label: 'Asist', value: '1' },
    ],
    tone: 'from-[#12648e] to-[#5A0E27]',
  },
  {
    id: '12',
    number: 70,
    name: 'Denis Drăguș',
    nationality: 'ROMANYA',
    isDomestic: false,
    positionGroup: 'fwd',
    positionCode: 'FOR',
    positionLabel: 'FORVET',
    rating: 8.2,
    age: 25,
    height: '1.85 m',
    note: 'Standard Liège Transferi',
    marketValue: 4_000_000,
    stats: [
      { label: 'Maç', value: '19' },
      { label: 'Gol', value: '5' },
      { label: 'Hız (km/h)', value: '34.2' },
    ],
    tone: 'from-[#3f2900] to-[#1A040B]',
  },
  {
    id: '13',
    number: 15,
    name: 'Stefan Savic',
    nationality: 'KARADAĞ',
    isDomestic: false,
    positionGroup: 'def',
    positionCode: 'STP',
    positionLabel: 'STOPER',
    rating: 8.0,
    age: 33,
    height: '1.87 m',
    note: 'Atlético Madrid',
    marketValue: 2_500_000,
    stats: [
      { label: 'Maç', value: '21' },
      { label: 'Top Çalma', value: '33' },
      { label: 'Hava %', value: '%68' },
    ],
    tone: 'from-[#544245] to-[#1A040B]',
  },
  {
    id: '14',
    number: 24,
    name: 'Pedro Malheiro',
    nationality: 'PORTEKİZ',
    isDomestic: false,
    positionGroup: 'def',
    positionCode: 'SB',
    positionLabel: 'SAĞ BEK',
    rating: 7.8,
    age: 23,
    height: '1.79 m',
    note: 'Boavista Transferi',
    marketValue: 4_200_000,
    stats: [
      { label: 'Maç', value: '16' },
      { label: 'Asist', value: '2' },
      { label: 'Orta %', value: '%28' },
    ],
    tone: 'from-[#12648e] to-[#34302b]',
  },
]
