import type { SquadDetailProfile } from './squadDetailTypes'

export const ratingScores = ['1.0', '2.0', '3.0', '3.5', '4.0', '4.5', '5.0'] as const

export const ratingFeedbackMap: Record<(typeof ratingScores)[number], string> = {
  '1.0': 'Zayıf Taktik (Geliştirilmeli)',
  '2.0': 'Eksik Dizilim (Savunma Zafiyeti Var)',
  '3.0': 'Orta Seviye Plan',
  '3.5': 'İyi Kurgulanmış Kadro',
  '4.0': 'Çok Başarılı Taktik',
  '4.5': 'Harika Taktik!',
  '5.0': 'Kusursuz Karadeniz Fırtınası!',
}

export const defaultSquadDetail: SquadDetailProfile = {
  id: '1',
  title: 'Akyazı Presi: Banza & Drăguș Çift Forvet Kuşatması',
  formationBadge: '4-2-3-1 (ASİMETRİK PRES DÜZENİ)',
  venueBadge: 'AKYAZI PAPARA PARK PLANLAMASI',
  verifiedBadge: 'ONAYLI TARAFTAR ANALİZİ',
  authorInitials: 'MR',
  authorUsername: '@MuratReis',
  authorBadge: 'Kıdemli Taktikçi',
  publishedLabel: '3 saat önce',
  locationLabel: 'Trabzon, TR',
  rating: 4.8,
  ratingCount: 342,
  approvalPercent: '%94',
  commentCount: 84,
  viewsLabel: '1.4k',
  tacticFitPercent: '%94',
  benchPlanLabel: 'İkinci Yarı Planı: Skor Koruma 3-5-2 Dönüşümü',
  avgAge: '26.2',
  avgAgeCaption: 'Süper Lig ortalamasının altında',
  totalValue: '68.5M€',
  totalValueCaption: 'Transfermarkt 2024 Güncel',
  foreignRuleLabel: 'UYGUN ✓',
  foreignRuleDetail: '8 Yabancı / 3 Yerli (Sahada)',
  authorNote:
    "Banza'nın ceza sahası içindeki sırtı dönük duvar olma kalitesi, arkadan fırlayan Drăguș ve içeri kat eden Višća için ölümcül koridorlar yaratıyor. Lundstram-Mendy ikilisi ise 2. bölge sahipsiz topları süpürüp oyunu hemen Akyazı tribününün arkasına itiyor.",
  authorNoteCredit: 'Murat Reis • Baş Taktik Editörü',
  pitchPlayers: [
    {
      id: 'st',
      shortName: 'S. Banza',
      fullName: 'Simon Banza',
      number: '99',
      positionLabel: 'ST',
      roleLabel: 'Hedef Santrfor',
      left: '50%',
      top: '6%',
      centerX: true,
      ringTone: 'primary-container',
      numberTone: 'primary',
      roleTone: 'primary',
      positionTone: 'primary',
      avatarInitials: 'SB',
      avatarGradient: 'from-[#3f2900] to-[#1A040B]',
    },
    {
      id: 'ss',
      shortName: 'D. Drăguș',
      fullName: 'Denis Drăguș',
      number: '70',
      positionLabel: 'SS / LW',
      roleLabel: 'Gölge Forvet',
      left: '24%',
      top: '20%',
      ringTone: 'primary',
      numberTone: 'secondary',
      roleTone: 'secondary',
      positionTone: 'primary',
      avatarInitials: 'DD',
      avatarGradient: 'from-[#5a0e27] to-[#1A040B]',
    },
    {
      id: 'cam',
      shortName: 'M. Cham',
      fullName: 'Muhammed Cham',
      number: '10',
      positionLabel: 'CAM (10 NO)',
      roleLabel: 'Kilit Pasör',
      left: '50%',
      top: '30%',
      centerX: true,
      ringTone: 'primary',
      numberTone: 'tertiary',
      roleTone: 'primary',
      positionTone: 'tertiary',
      avatarInitials: 'MC',
      avatarGradient: 'from-[#12648e] to-[#1A040B]',
    },
    {
      id: 'rw',
      shortName: 'E. Višća',
      fullName: 'Edin Višća',
      number: '7',
      positionLabel: 'RW',
      roleLabel: 'İçe Kat Eden Kanat',
      left: '80%',
      top: '24%',
      ringTone: 'primary',
      numberTone: 'secondary',
      roleTone: 'primary',
      positionTone: 'primary',
      avatarInitials: 'EV',
      avatarGradient: 'from-[#12648e] to-[#3a0014]',
    },
    {
      id: 'ldm',
      shortName: 'J. Lundstram',
      fullName: 'John Lundstram',
      number: '5',
      positionLabel: 'LDM',
      roleLabel: 'Top Dağıtıcı',
      left: '34%',
      top: '48%',
      ringTone: 'surface',
      numberTone: 'primary',
      roleTone: 'on-surface',
      positionTone: 'secondary',
      avatarInitials: 'JL',
      avatarGradient: 'from-[#544245] to-[#1A040B]',
    },
    {
      id: 'rdm',
      shortName: 'B. Mendy',
      fullName: 'Batista Mendy',
      number: '6',
      positionLabel: 'RDM',
      roleLabel: 'Şok Pres • Çapa',
      left: '66%',
      top: '48%',
      ringTone: 'surface',
      numberTone: 'primary',
      roleTone: 'primary-container',
      positionTone: 'secondary',
      avatarInitials: 'BM',
      avatarGradient: 'from-[#5a0e27] to-[#12648e]',
    },
    {
      id: 'lb',
      shortName: 'E. Elmalı',
      fullName: 'Eren Elmalı',
      number: '18',
      positionLabel: 'LB',
      roleLabel: 'Savunmacı Bek',
      left: '12%',
      top: '66%',
      ringTone: 'surface',
      numberTone: 'secondary',
      roleTone: 'surface',
      positionTone: 'primary',
      avatarInitials: 'EE',
      avatarGradient: 'from-[#75B7E5] to-[#1A040B]',
    },
    {
      id: 'lcb',
      shortName: 'A. Batagov',
      fullName: 'Arseniy Batagov',
      number: '44',
      positionLabel: 'LCB',
      roleLabel: 'Oyun Kuran Stoper',
      left: '33%',
      top: '70%',
      ringTone: 'surface',
      numberTone: 'primary',
      roleTone: 'on-surface',
      positionTone: 'primary',
      avatarInitials: 'AB',
      avatarGradient: 'from-[#3a0014] to-[#1A040B]',
    },
    {
      id: 'rcb',
      shortName: 'S. Savić',
      fullName: 'Stefan Savić',
      number: '15',
      positionLabel: 'RCB',
      roleLabel: 'Hava Hakimiyeti',
      left: '67%',
      top: '70%',
      ringTone: 'surface',
      numberTone: 'primary',
      roleTone: 'primary',
      positionTone: 'primary',
      avatarInitials: 'SS',
      avatarGradient: 'from-[#5a0e27] to-[#1A040B]',
    },
    {
      id: 'rb',
      shortName: 'P. Malheiro',
      fullName: 'Pedro Malheiro',
      number: '79',
      positionLabel: 'RB',
      roleLabel: 'Kanat Bindirme',
      left: '88%',
      top: '66%',
      ringTone: 'surface',
      numberTone: 'secondary',
      roleTone: 'secondary',
      positionTone: 'primary',
      avatarInitials: 'PM',
      avatarGradient: 'from-[#12648e] to-[#1A040B]',
    },
    {
      id: 'gk',
      shortName: 'U. Çakır',
      fullName: 'Uğurcan Çakır',
      number: '1',
      positionLabel: 'GK',
      roleLabel: 'Süpürücü Kaleci',
      left: '50%',
      bottom: '4%',
      centerX: true,
      ringTone: 'secondary-container',
      numberTone: 'primary',
      roleTone: 'primary',
      positionTone: 'primary',
      isCaptain: true,
      avatarInitials: 'UÇ',
      avatarGradient: 'from-[#8ccefd] to-[#5a0e27]',
    },
  ],
  benchPlayers: [
    { number: '24', position: 'ST', name: 'U. Bozok', role: 'Ceza Sahası', roleTone: 'primary' },
    { number: '11', position: 'RW', name: 'O. Tufan', role: 'Dinamizm', roleTone: 'secondary' },
    { number: '8', position: 'CM', name: 'E. Bardhi', role: 'Duran Top', roleTone: 'tertiary' },
    { number: '20', position: 'CB', name: 'H. Türkmen', role: 'Hava Topu', roleTone: 'muted' },
    {
      number: '9',
      position: 'LW',
      name: 'A. Nwakaeme',
      role: 'Sihirbaz',
      roleTone: 'bold-primary',
    },
    { number: '25', position: 'GK', name: 'O. Çevikkan', role: 'Genç Kaleci', roleTone: 'muted' },
  ],
  instructions: [
    {
      title: 'Hücum Anlayışı & Pres Hattı',
      headline: 'Yüksek Şok Pres & Kanat İzolasyonu',
      body: 'Top rakip stoperdeyken Banza ve Drăguș ikili kıskaç uygular; Cham merkez pas koridorunu kilitler.',
    },
    {
      title: 'Savunma Çizgisi',
      headline: 'Orta Saha İlerisi (Agresif Ofsayt Tuzağı)',
      body: "Savić hattı 45 metrede tutarak geriye kaçan toplarda Uğurcan'ın süpürücü aksiyonuna alan bırakır.",
    },
    {
      title: 'Tempo & Genişlik',
      headline: 'Hızlı Pas & Dar Alan Çıkışları',
      body: 'Sol kanatta Elmalı içeride kalırken, sağ kanatta Malheiro tüm koridoru kat eder.',
    },
    {
      title: 'Duran Top Sorumluları',
      headline: 'Muhammed Cham (Sol Ayak) • Edin Višća (Sağ Ayak)',
      body: 'Ön direk koşularında Mendy ve Savić birincil hava hedefidir.',
      headlineTone: 'primary',
    },
  ],
  comments: [
    {
      id: 'c1',
      initials: 'AK',
      displayName: 'Ahmet Köse',
      badge: 'Kombineli Taraftar',
      badgeTone: 'surface',
      avatarTone: 'primary',
      timeLabel: '42 dakika önce',
      body: "Mendy'nin sağ stoper önüne süpürücü konması Malheiro'nun hücum bindirmelerini inanılmaz rahatlatır. Gaziantep maçında gördük, Malheiro çizgiyi aldığında Višća içeri girip ikinci forvet oluyor. Bu kadro Akyazı'da ilk 20 dakikada maçı koparır! Eline sağlık Murat Reis.",
      upvotes: 68,
      downvotes: 2,
      replyCount: 3,
    },
    {
      id: 'c2',
      initials: 'BY',
      displayName: 'Barış Yavuz',
      badge: 'Gurbetçi Fırtına',
      badgeTone: 'secondary',
      avatarTone: 'secondary',
      timeLabel: '1 saat önce',
      body: "Tek çekincem sol bekte Eren Elmalı'nın yalnız kalması. Drăguș geriye yardım etmezse sol koridordan geçiş yiyebiliriz. Nwakaeme 65'te girip Drăguș ile değiştiğinde tempoyu nasıl ayarlayacağız? Bence oraya Lundstram daha fazla kaymalı.",
      upvotes: 34,
      downvotes: 5,
      replyCount: 1,
    },
    {
      id: 'c3',
      initials: 'SK',
      displayName: 'Selin Kaya',
      badge: 'Taktik Analist',
      badgeTone: 'surface',
      avatarTone: 'primary-container',
      timeLabel: '2 saat önce',
      body: "Cham'ın 10 numara serbestliği bu dizilişte gerçekten kritik. Banza sırtı dönük tutarken Cham'ın yarı alan girişi golü getirir. Puanım 4.5 — savunma hattı biraz daha kompakt olsa 5.",
      upvotes: 21,
      downvotes: 1,
      replyCount: 0,
    },
  ],
}

export const squadDetailById: Record<string, SquadDetailProfile> = {
  '1': defaultSquadDetail,
}
